name: 🧼 SwiftFormat

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  swiftformat:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat in Strict Mode
        run: swiftformat . --strict
