# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDemo1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDemo1
  pod 'DropDown'

end

# 👇 This is the magic line
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$BUILD_DIR/$CONFIGURATION$EFFECTIVE_PLATFORM_NAME'
    end
  end
end
