disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - unused_import

included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.swift

line_length:
  warning: 120
  error: 140

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 60
    error: 80

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level: 2
  statement_level: 5