# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tussly' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tussly
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'ReachabilitySwift'
  pod 'GoogleSignIn'
  pod 'SDWebImage'
  pod 'DynamicCodable'
  pod 'ListPlaceholder'
  pod 'SwipeCellKit'
  pod 'CropViewController'
  pod 'MarqueeLabel'

  pod 'Firebase/Firestore', '~> 11.15.0'
  pod 'Firebase/Crashlytics', '~> 11.15.0'
  pod 'Firebase/Analytics', '~> 11.15.0'
  pod 'FirebaseCore', '~> 11.15.0'
  pod 'FirebaseMessaging', '~> 11.15.0'
  
  #pod 'ShipBookSDK' #'1.1.19'
  pod 'CometChatSDK'#, '4.0.54'
  pod "PostHog", "~> 3.0"
  pod 'DropDown'
  
end
