# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodFlocker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodFlocker
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'CropViewController'
  pod 'IQKeyboardManagerSwift'
  pod 'GoogleMaps'
  pod 'FloatingPanel'
  pod 'SwiftGifOrigin'
  pod 'SDWebImage'
  pod 'ActionSheetPicker-3.0'
  pod 'ABVideoRangeSlider'
  pod 'FloatRatingView'
  pod "CCValidator"
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Crashlytics'
  pod 'TTTAttributedLabel'

end
